name: Dimi Tech
description: >
  Dimi Tech
encoding: utf-8
about: >
  <br>
  Hi, I'm Dimi.
  <br>
  <br>
  Computers are my main obsession, but I'm also into audio, extreme sports, philosophy etc...
  <br>
  <br>
  I mostly program for the web although I dabble in C/C++ and graphics programming as well.
  <br>
  <br>
  Feel free to hit me up at: <a href="mailto:dusan_dimitric@yahoo.com">dusan_dimitric@yahoo.com</a>
master_repo: false
url: "https://dimitech.io"
markdown: kramdown
highlighter: rouge

plugins: ["jekyll-paginate", "jekyll-gist", "jekyll-feed"]

paginate: 8

logo: logo.png
disqus_shortname:

rtl: false
owner:
  name: Dimi - Dušan Dimitrić
  avatar: "https://avatars0.githubusercontent.com/u/14316093?s=200&v=4"
  email: "dusan_dimitric@yahoo.com"
  youtube: https://www.youtube.com/channel/UCKqX92EEpKK40PXJTZ58ejw
  github: https://github.com/DimiTech
  linkedin: https://rs.linkedin.com/in/dusan-dimitric

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
